name: EoAF
channels:
  - conda-forge
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cachecontrol=0.13.1
  - cachecontrol-with-filecache=0.13.1
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - cleo=2.1.0
  - colorama=0.4.6
  - crashtest=0.4.1
  - distlib=0.3.8
  - dulwich=0.21.7
  - filelock=3.13.1
  - idna=3.6
  - importlib-metadata=7.0.1
  - jaraco.classes=3.3.1
  - keyring=24.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.26
  - libsqlite=3.45.1
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - more-itertools=10.2.0
  - msgpack-python=1.0.7
  - ncurses=6.4
  - numpy=1.26.4
  - openssl=3.2.1
  - packaging=23.2
  - pexpect=4.9.0
  - pip=24.0
  - pkginfo=1.9.6
  - platformdirs=3.11.0
  - poetry=1.7.1
  - poetry-core=1.8.1
  - poetry-plugin-export=1.6.0
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-build=1.0.3
  - python-fastjsonschema=2.19.1
  - python-installer=0.7.0
  - python_abi=3.12
  - rapidfuzz=3.6.1
  - readline=8.2
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - setuptools=69.1.0
  - shellingham=1.5.4
  - tk=8.6.13
  - tomli=2.0.1
  - tomlkit=0.12.3
  - trove-classifiers=2024.1.31
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.2.1
  - virtualenv=20.25.1
  - wheel=0.42.0
  - xattr=0.10.1
  - xz=5.2.6
  - zipp=3.17.0